### ISSUE TITLE
Does not handle NaN values.

### ISSUE THREAD

**Issue by 5nefarious** [andreyvit/json-diff#32]
```
                        "cc": NaN,
                              ^

SyntaxError: Unexpected token N
    at Object.parse (native)
    at module.exports (/mnt/c/Users/REDACTED/node_modules/json-diff/lib/cli.js:31:18)
    at Object.<anonymous> (/mnt/c/Users/REDACTED/node_modules/json-diff/bin/json-diff.js:2:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by ewoudenberg** [comment]
Unfortunately JSON.parse cannot handle NaN or the Infinities.
See: ECMAScript 2021 Language spec, JSON.stringify section, note 4: 
```
NOTE 4
Finite numbers are stringified as if by calling ToString(number). NaN and Infinity regardless of sign are represented as the String "null".
```
From: https://262.ecma-international.org/12.0/#sec-json.stringify
